DS.HeartSummer.WebApp/Controllers/SummerController.cs
using DS.HeartSummer.BLL;
using DS.HeartSummer.IBLL;
using DS.HeartSummer.Model;
using DS.HeartSummer.Common;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using DS.HeartSummer.WebApp.Models.Wechat;
using System.Drawing;
using System.Text.RegularExpressions;
using System.Web.Caching;

namespace DS.HeartSummer.WebApp.Controllers
{
    public class SummerController : WeChatController
    {
        // GET: Summer

        WeChatHelper wh = new WeChatHelper();
        IBLL.IStudentGradesService stuGradService = new BLL.StudentGradesService(); 
        IBLL.IStudentInfoService stuInfoService = new BLL.StudentInfoService();
        IBLL.ITermsService termService = new BLL.TermsService();
        IBLL.IStudentImageTableService stuImgService = new BLL.StudentImageTableService();  
        public ActionResult Index()
        {
            return Content("");
        }

        #region 导入学员信息
        public ActionResult LoginJxxy()
        {
            string sessionId = HttpHelper.GetHeaderByRequest("http://jwxt.fjjxu.edu.cn/_data/index_LOGIN.aspx", "get", "", "Set-Cookie");
            sessionId = sessionId.Substring(18, 24);

            string read = HttpHelper.CreateHttpRequest("http://jwxt.fjjxu.edu.cn/_data/index_LOGIN.aspx", "get", "");
            Regex reg = new Regex(@"(?is)<input[^/>]* type=(?<hidden>\S*)[^/>]* name=(?<__VIEWSTATE>\S*) [^/>]*/>");
            read = reg.Match(read).ToString();

            read = read.Substring(47, read.Length - 51);



            string hiddenState = Uri.EscapeDataString(read);
            CacheHelper.Set("hiddenState", hiddenState);

            Session["sessionId"] = sessionId;
            return View();
        }

        [HttpPost]
        public ActionResult LoginJxxy(string LoginId, string LoginPwd, string ValiCode)
        {
            if (CacheHelper.Exist("hiddenState") && LoginId != "" && LoginPwd != "" && ValiCode != "")
            {
                string vewState = @"__VIEWSTATE=" + CacheHelper.Get("hiddenState") + "&Sel_Type=STU&txt_sdsdfdsfryuiighgdf=" + LoginId + "&txt_dsfdgtjhjuixssdsdf=" + LoginPwd + "&txt_sftfgtrefjdndcfgerg=" + ValiCode.ToUpper() + "&typeName=%D1%A7%C9%FA&sdfdfdhgwerewt=" + HttpHelper.MD5Calc(LoginId + HttpHelper.MD5Calc(LoginPwd).Substring(0, 30).ToUpper() + "13763").Substring(0, 30).ToUpper() + "&cxfdsfdshjhjlk=" + HttpHelper.MD5Calc(HttpHelper.MD5Calc(ValiCode.ToUpper()).Substring(0, 30).ToUpper() + "13763").Substring(0, 30).ToUpper();

                CookieContainer cookies = new CookieContainer();
                cookies.Add(new Uri("http://jwxt.fjjxu.edu.cn/"), new Cookie("ASP.NET_SessionId", Session["sessionId"].ToString()));
                string ret = HttpHelper.FullCreateHttpRequest("http://jwxt.fjjxu.edu.cn/_data/index_LOGIN.aspx", "post", vewState, "jwxt.fjjxu.edu.cn", "http://jwxt.fjjxu.edu.cn/_data/index_LOGIN.aspx", cookies);


                Regex reg = new Regex("<span id=\"divLogNote\">[^/]*");


                string read = reg.Match(ret).ToString();
                read = read.Substring(40, read.Length - 40);
                //登录成功！
                //<table[^>]*>[\s\S]*?</table> 匹配table
                //开始导入数据
                if (read == "正在加载权限数据...<")
                {

                    //GetStudentClassTable("20151", cookies);
                    //开始成绩导入
                    BatchProCourseData(cookies, LoginId, LoginPwd);
                    //return Content();
                    return Content("0");
                }
                else
                {
                    return Content(read);

                }

            }
            else
            {
                return null;
            }
        }

        private string BatchProCourseData(CookieContainer cookies, string loginId, string loginPwd)
        {
          
            List<Terms> tls = termService.LoadEntities(C => true).ToList();
            foreach (Terms t in tls)
            {

                string data = "sel_xnxq=" + t.Term + "&radCx=1";
                string html = HttpHelper.FullCreateHttpRequest("http://jwxt.fjjxu.edu.cn/xscj/c_ydcjrdjl_rpt.aspx", "post", data, "jwxt.fjjxu.edu.cn", "http://jwxt.fjjxu.edu.cn/_data/index_LOGIN.aspx", cookies);
                //开始导入

                ProHtmlCourseData(html, loginId, loginPwd, t.Term, cookies);

            }
            GetStudentClassTable("20151", cookies, loginId);
            return "导入成功！";
        }
        /// <summary>
        /// 处理数据
        /// </summary>
        /// <param name="html"></param>
        private string ProHtmlCourseData(string html, string userId, string userPwd, string term, CookieContainer cookies)
        {
            string userName = "";
            try
            {
                //避免传入数据为空
                Regex r = new Regex("姓名[^<]*");//获取姓名
                userName = r.Match(html).ToString();
                userName = userName.Substring(3, userName.Length - 3);

            }
            catch (Exception)
            {
            }
            if (userName != "")
            {
                //获取主要数据段
                Regex r2 = new Regex("<td width=25% align=left[^鑒]*</form>");
                html = r2.Match(html).ToString();

                //去除html标签
                Regex r3 = new Regex("<[^>]*>");

                html = r3.Replace(html, "\n");

                string[] ss = html.Split(new char[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
                //找到   姓名[^<]*  传入学号 密码  学期
                //<td width=25% align=left[^()]*</form>   一层筛选
                //<[^>]*> 替换html  二层
                int i = 0;
             
                //判断是否已经存在
                StudentInfo stuInfo = new StudentInfo();
                stuInfo.UserName = userName;
                stuInfo.UserId = userId;
                stuInfo.UserPwd = userPwd;
                int stuinfoid = stuInfoService.GetExistOrCreate(stuInfo).Id;

                stuGradService.DeleteEntities(c => c.UserInfoId == stuinfoid && c.Term == term);
                while ((i + 7) < ss.Count())
                {
                    StudentInfo si = stuInfoService.GetExistOrCreate(stuInfo);
                    StudentGrades sgs = new StudentGrades();
                    sgs.Term = term;
                    sgs.Course = ss[i++];
                    sgs.Credit = ss[i++];
                    sgs.CourseType = ss[i++];
                    sgs.Quality = ss[i++];
                    sgs.CheckMode = ss[i++];
                    sgs.PrimiGrade = ss[i++];
                    sgs.ValidGrade = ss[i++];
                    sgs.Mark = ss[i++];
                    si.StudentGrades.Add(sgs);
                    stuInfoService.UpdateEntity(si);
                }
                StudentInfo stuInfoWithTable = stuInfoService.GetExistOrCreate(stuInfo);

                return "导入数据成功！";
            }
            else
            {
                return null;
            }
        }


        public ActionResult LoginJxxyGetValiDate()
        {
            if (Session["sessionId"] != null)
            {
                CookieContainer cookies = new CookieContainer();
                cookies.Add(new Uri("http://jwxt.fjjxu.edu.cn/"), new Cookie("ASP.NET_SessionId", Session["sessionId"].ToString()));

                Image i = HttpHelper.CreateHttpRequestReturnImage("http://jwxt.fjjxu.edu.cn/sys/ValidateCode.aspx", "get", "", cookies);
                byte[] s = HttpHelper.GetByteImage(i);
                return File(s, "image/jpeg");
            }
            else
            {
                return null;
            }

        }


        #endregion
        #region 获取图表
        /// <summary>
        /// 获取考试相关//ok
        /// </summary>
        /// <param name="term"></param>
        /// <param name="cookies"></param>
        /// <returns></returns>
        private string GetStudentExamTable(string term, CookieContainer cookies)
        {
            //string data = "type=1&w=1110&h=240&xnxq=" + term;

            //http://jwxt.fjjxu.edu.cn/znpk/Pri_StuSel_rpt.aspx?m=vhnn70MGbc99CRN
            string m = HttpHelper.GetRandonString(15);
            string hidsjyzm = HttpHelper.MD5Calc("13763" + term + m).ToUpper();

            string gethidyzm = HttpHelper.CreateHttpRequest("http://jwxt.fjjxu.edu.cn/znpk/Pri_StuSel.aspx", "get", "", cookies);
            //<input type="hidden" name="hidyzm" value="eaeeab3da91596c811ca97a67c3713z">
            Regex reg = new Regex("<input type=\"hidden\" name=\"hidyzm\" value=\"[0-9a-z]*\">");
            gethidyzm = reg.Match(gethidyzm).ToString();

            gethidyzm = gethidyzm.Substring(42, gethidyzm.Length - 44);



            string data = "sel_xnxq=20141&sel_lc=2014106%2C2014-2015%D1%A7%C4%EA%B5%DA%B6%FE%D1%A7%C6%DA%C6%DA%C4%A9%BF%BC%CA%D4&btn_search=%BC%EC%CB%F7";


            string res = HttpHelper.FullCreateHttpRequest("http://jwxt.fjjxu.edu.cn/KSSW/stu_ksap_rpt.aspx", "post", data, "jwxt.fjjxu.edu.cn", "http://jwxt.fjjxu.edu.cn/KSSW/stu_ksap.aspx", cookies);



            Image i = HttpHelper.CreateHttpRequestReturnImage("http://jwxt.fjjxu.edu.cn/KSSW/stu_ksap_drawimg.aspx?w=1029&h=100&kslc=2014106", "jwxt.fjjxu.edu.cn", "http://jwxt.fjjxu.edu.cn/KSSW/stu_ksap_rpt.aspx", "get", "", cookies);
            i.Save(@"D:\Users\Administrator\Desktop\1.jpg");
            return "ok";
        }
        private string GetStudentClassTable(string term, CookieContainer cookies, string userId)
        {

            //http://jwxt.fjjxu.edu.cn/znpk/Pri_StuSel_rpt.aspx?m=W8SEuHqlrfJNqG4

            string m = HttpHelper.GetRandonString(15);
            string hidsjyzm = HttpHelper.MD5Calc("13763" + term + m).ToUpper();
            string gethidyzm = HttpHelper.CreateHttpRequest("http://jwxt.fjjxu.edu.cn/znpk/Pri_StuSel.aspx", "get", "", cookies);

DS.HeartSummer.WebApp/Views/Summer/AddButton.cshtml
@model DS.HeartSummer.Model.CustomMenu

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddButton</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>CustomMenu</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

DS.HeartSummer.WebApp/Views/Summer/GetSchoolCalendar.cshtml
@{
    ViewBag.Title = "校历";
    Layout = "~/Views/Shared/_WechatJssdkMaste.cshtml";
}

@section head{
<script>
    wx.ready(function () { 
        wx.hideAllNonBaseMenuItem(); 
                wx.previewImage({
                    current: 'http://www.codefirst.top/Models/xl.jpg',
                    urls: [ 
                      'http://www.codefirst.top/Models/xl.jpg'
                    ]
                });

        });
</script>

}
 

DS.HeartSummer.WebApp/Views/Summer/GetSutentAllDate.cshtml
@using DS.HeartSummer.WebApp.Models.Wechat;
@{
    Layout = null;
}
<!DOCTYPE html>
<html> 
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <title>成绩信息</title>  
    <link rel="shortcut icon" href="favicon.ico">
    <link href="~/Content/css/bootstrap.min14ed.css?v=3.3.6" rel="stylesheet">
    <link href="~/Content/css/font-awesome.min93e3.css?v=4.4.0" rel="stylesheet">
    <link href="~/Content/css/animate.min.css" rel="stylesheet">
    <link href="~/Content/css/style.min862f.css?v=4.1.0" rel="stylesheet">
</head>
<body class="gray-bg">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row"> 
            @{ 
                List<ShowGrade> sgList = ViewData["showData"] as List<ShowGrade>;
            }
            @foreach (ShowGrade sg in sgList)
            {
                <div class="col-sm-6">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>@sg.Term</h5>
                        </div>
                        <div class="ibox-content">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>科目</th>
                                        <th>学分</th>
                                        <th>成绩</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (GradeDate gd in sg.GradeDates)
                                    {
                                        <tr>

                                            <td>@gd.GradeName</td>
                                            <td>@gd.Credit</td>
                                            <td>@gd.Grade</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>
    <script src="~/Content/js/jquery.min.js?v=2.1.4"></script>
    <script src="~/Content/js/bootstrap.min.js?v=3.3.6"></script> 
</body> 
</html>

DS.HeartSummer.WebApp/Views/Summer/LoginJxxy.cshtml
@using DS.HeartSummer.WebApp.Models.Wechat;
@{
    ViewBag.Title = "LoginJxxy";
    Layout = "~/Views/Shared/_LoginMaster.cshtml";
}
@section head{

    <script src="https://res.wx.qq.com/open/js/jweixin-1.0.0.js" type="text/javascript"></script>
    <script src="~/Content/js/plugins/sweetalert/sweetalert.min.js"></script>
    <link href="~/Content/css/plugins/sweetalert/sweetalert.css" rel="stylesheet" />
    <script>
        @{
            WeChatHelper wh = new WeChatHelper();

            WeChatJssdk wj = wh.GetJssdk(Request.Url.AbsoluteUri);
            }
        wx.config({
            debug: false, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
            appId: '@wj.AppId', // 必填，公众号的唯一标识
            timestamp: @wj.Timestamp, // 必填，生成签名的时间戳
            nonceStr: '@wj.Noncestr', // 必填，生成签名的随机串
            signature: '@wj.Signature',// 必填，签名，见附录1
            jsApiList:[
        'checkJsApi',
       'previewImage',
       'hideAllNonBaseMenuItem',
       'closeWindow'

            ] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2
        });
        wx.ready(function () {
            wx.hideAllNonBaseMenuItem();
        })
    </script>
}

<div class="middle-box text-center loginscreen  animated fadeInDown">
    <div>
        <div>
            <h2 class="author-name">教务查询</h2>
        </div>
        <br />
        @using (Ajax.BeginForm("LoginJxxy", "Summer", new AjaxOptions { OnSuccess = "success", OnBegin = "Begin" }))
        {
            <div class="form-group">
                <input type="text" class="form-control" name="LoginId" placeholder="学号" required="">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="LoginPwd" placeholder="密码" required="">
            </div>

            <div class="form-group">
                <input type="text" class="form-control" name="ValiCode" placeholder="验证码" required="">
            </div>

            <img src="LoginJxxyGetValiDate" alt="Alternate Text" onclick="$(this).attr('src', 'LoginJxxyGetValiDate?v=' + Math.random())" style="cursor:pointer;" />
            <button type="submit" class="btn btn-primary block full-width m-b">登 录</button>
        }
    </div>
</div>
<a href="#" style="display:none" class="btn btn-xs btn-primary" data-toggle="modal" data-target="#myModal1" id="showload">显示载入层</a>
<div class="modal inmodal in" id="myModal1" tabindex="-1" role="dialog" aria-hidden="true" style="display:none;">
    <div class="modal-dialog cm-invalidchar" style="padding-top:300px">

        <div class="sk-spinner sk-spinner-double-bounce">
        </div>

    </div>
</div>

@section script{
    <script>
        function success(e){
            if (e == "0") {
                $("#showload").click(); 
                swal({
                    title:"导入成功！",
                    text:"可在微信中回复学号或者姓名进行查询！", 
                },function(){ 
                    wx.closeWindow(); 
                }); 
            }
            else {
                swal(e);
                $("#showload").click();
            }
        }
        function Begin() {
            $("#showload").click(); 
            swal({
                title:"成功进行导入！", 
                text:"可稍后在微信中回复成绩#学号或者成绩#姓名进行查询！（记得要加上成绩#哦）", 
            },function(){ 
                wx.closeWindow(); 
            }); 
        }  
    </script>
}

DS.HeartSummer.WebApp/Views/Summer/ShowStudentTable.cshtml
@{
    ViewBag.Title = "ShowStudentTable";
    Layout = "~/Views/Shared/_WechatJssdkMaste.cshtml";
}
 
@section head{
    <script>
    wx.ready(function () {
        wx.hideAllNonBaseMenuItem();
                wx.previewImage({
                    current: 'http://www.codefirst.top/summer/getstudentclasstable?userinfoid=149&term=20151',
                    urls: [
                      'http://www.codefirst.top/summer/getstudentclasstable?userinfoid=149&term=20151'
                    ]
                });

        });
    </script>

}